server:
  port: 9999
spring:
  application:
    name: shirodemo
  datasource:
     druid:
       username: root
       password: beans123
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/shiro?useEncoding=true&characterEncoding=utf-8
     type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  config-location: classpath:mybatisconfig.xml
  mapper-locations: classpath:mappers/*.xml